### ISSUE TITLE
fatal error: 'exchange/market_state.hpp' file not found

### ISSUE THREAD

**Issue by oneroot001** [EOSIO/eosio.wasmsdk#32]
when I compile exchange contract with "eosio-cpp",it failed:
./exchange.hpp:6:10: fatal error: 'exchange/market_state.hpp' file not found
#include <exchange/market_state.hpp>

How to solve this?

**Comment by larryk85** [comment]
Did you add the include path for where market_state.hpp is?  Are you using the cmake method or just eosio-cpp to compile the contract?

**Comment by oneroot001** [comment]
I use eosio-cpp command to compile the contract and it has the above errors.When I use cmake method.the error is:
include could not find load file:

    EosioWasmToolchain

**Comment by 86chenjie** [comment]
same here.

**Comment by vjoke** [comment]
The reported error shows that WASM_ROOT is not set properly. 
You can check if the file `/usr/local/eosio.wasmsdk/lib/cmake/EosioWasmToolchain.cmake` exists and set it as below 
```
set(WASM_ROOT "/usr/local/eosio.wasmsdk") 
```
