### ISSUE TITLE
Better build error message when not enough memory free

### ISSUE THREAD

**Issue by liamcurry** [EOSIO/eosio.wasmsdk#35]
When building with the `./build.sh` script if you don't have enough free memory then `CORES` will be set to `0` on this line:

https://github.com/EOSIO/eosio.wasmsdk/blob/master/build.sh#L71

This is later passed on to `make` as `make -j 0`, which throws an error because `-j` must be greater than zero. It would be nice if the build failed early with a nice error message instead.

FYI I ran into this issue while building in a Docker container and fixed it by allocating more memory to the container (with the `--memory` flag).

**Comment by larryk85** [comment]
Resolved by PR #44
