### ISSUE TITLE
eosio-cpp error: fatal error: 'boost/hana.hpp' file not found

### ISSUE THREAD

**Issue by 86chenjie** [EOSIO/eosio.wasmsdk#46]
/usr/local/eosio.wasmsdk/bin/../include/eosiolib/multi_index.hpp:9:10: fatal error: 'boost/hana.hpp' file not found.

besides, i use cmake .  on "examples/hello/" which no error, but no wasm file generated. 
what's the proper way to generate wasm file ?

**Comment by larryk85** [comment]
Add ```TEMP_DIR='/tmp'``` to build.sh at line 12.

**Comment by larryk85** [comment]
Resolved by PR #62
