### ISSUE TITLE
Add EosioTesterBuild.cmake

### ISSUE THREAD

**Issue by cz-it** [EOSIO/eosio.wasmsdk#71]
How about add EosioTesterBuild.cmake.in in "eosio.wasmsdk/modules". Then we can add unit test for contract developing.Otherwise we need install eos first.

**Comment by larryk85** [comment]
You don't need to install eos to use the cmake system for tester.  If you have copied the way to do this from eosio.contracts, the only thing you need to do is set EOSIO_ROOT to the build directory of eos.

**Comment by cz-it** [comment]
Without eos. the EosioTester will be not found when make eosio.contract(https://github.com/EOSIO/eosio.contracts)
